### ISSUE TITLE
Token is not getting saved even after successful authentication 

### ISSUE THREAD

**Issue by bmharsha** [JuliaComputing/PkgAuthentication.jl#2]
This issue was reported by @abhijithch on JuliaPro slack, he saw this issue happening to a Pumas workshop attendee, below, I'm pasting the exact phrase

```
After seeing successfull authentication message on the IDE, the auth.toml file is still not present in the folder where it should be.

```

**Comment by pfitzseb** [comment]
Let's hope this is fixed with the new implementation.
