### ISSUE TITLE
PkgAuthentication.jl is not invoking the auth mechanism

### ISSUE THREAD

**Issue by bmharsha** [JuliaComputing/PkgAuthentication.jl#3]
This issue was reported by @abhijithch in a private chat, he saw this issue happening to a Pumas workshop attendee.

PkgAuthentication.jl is not invoking the auth mechanism even though the token has expired / invalid. We were encountering below error
![WhatsApp Image 2020-02-25 at 2 19 38 PM](https://user-images.githubusercontent.com/5441491/75248307-f3fae200-57f9-11ea-8c85-cb1991f78bcc.jpeg)

Above issue got resolved by manually deleting the auth.toml and re-downloading it. PkgAuthentication.jl should have invoked the authentication mechanism if the token was invalid / corrupted.

**Comment by pfitzseb** [comment]
Let's hope this is fixed with the new implementation.
